config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'settings/profile' => 'profiles#edit'
  put 'settings/profile' => 'profiles#update'

  get 'settings/password' => 'profiles#edit_password'
  put 'settings/password' => 'profiles#update_password'

  resources :candidatos, only: [:index] do
    member do
      get 'biografia'
      get 'fotos'
      get 'propostas'
    end
  end

  resources :cidades, only: [] do
    get :list_cidade_estado, on: :collection
  end

  resources :demandas, except: [:edit, :update] do
    resources :comments, only: [:create]
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state

  def self.cidade_estado(q)
    City.joins(:state)
      .select("cities.id, cities.name, states.name as state_name")
      .where("cities.name like ?", "%#{q}%")
      .limit(10)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates_presence_of :content, :user_id
end

app/models/demanda.rb
class Demanda < ActiveRecord::Base
  belongs_to :user
  belongs_to :demanda_categoria

  has_many :comments, as: :commentable

  validates_presence_of :titulo, :descricao, :demanda_categoria_id
  validate :map_address_selected?

  def map_address_selected?
    unless latitude.present? || longitude.present?
      errors.add :endereco, "can't be blank"
    end
  end
end

app/models/demanda_categoria.rb
class DemandaCategoria < ActiveRecord::Base
  validates_presence_of :name
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :city
  has_many :demandas, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Paperclip configuration
  has_attached_file :picture, styles: {medium: "300x300", thumb: "100x100"},
    default_url: "/images/missing.png"

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  validates :partido_id, presence: true, if: :candidato?
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  validates_presence_of :city_id

  def primeiro_nome
    all_names.first
  end

  def ultimo_nome
    all_names.last
  end

  def all_names
    name.split
  end

  def self.candidatos
    where candidato: 1
  end

  def candidato?
    candidato.to_i == 1
  end

  def eleitor?
    !candidato?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit :username, :name, :partido_id, :candidato, :email, :password,
               :password_confirmation, :city_id
    end
  end
end

app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
  before_action :authenticate_user!
  after_action :redirect_unless_candidato, except: [:index]

  def index
    @candidatos = User.candidatos
  end

  def biografia
    @user = User.find params[:id]
  end

  def propostas
    @user = User.find params[:id]
  end

  private
  def redirect_unless_candidato
    unless @user.candidato?
      redirect_to root_path
    end
  end

end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  layout false

  def list_cidade_estado
    @cidades = City.cidade_estado params[:q]
    render json: @cidades
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @resource = if params[:demanda_id].present?
      Demanda.find params[:demanda_id]
    end

    @comment = @resource.comments.build comment_params
    @comment.user = current_user
    @comment.save

    @comments = @resource.comments
    @demanda  = @resource

    render "create.js.erb"
  end

  private
    def comment_params
      params.require(:comment).permit :content
    end
end

app/controllers/demandas_controller.rb
class DemandasController < ApplicationController
  before_action :authenticate_user!

  def index
    @demandas = Demanda.all
  end

  def new
    @demanda = Demanda.new
  end

  def create
    @demanda = Demanda.new demanda_params
    @demanda.user = current_user
    respond_to do |format|
      if @demanda.save
        format.js {render js: "window.location = '#{demandas_path}'"}
      else
        format.js
      end
    end
  end

  def show
    @demanda = Demanda.find params[:id]
    @comments = @demanda.comments
  end

  private
    def demanda_params
      params.require(:demanda).permit :latitude, :longitude, :titulo, :descricao,
                                      :demanda_categoria_id
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update user_params
      if @user.candidato?
        redirect_to biografia_candidato_path(@user)
      else
        redirect_to eleitor_candidato_path(@user)
      end
    else
      render :edit
    end
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_with_password password_params
      sign_in @user, bypass: true
      redirect_to root_path
    else
      render :edit_password
    end
  end

  private
  def user_params
    permitted_params = params.require(:user)
                             .permit(:email, :username, :name, :candidato,
                                     :partido_id, :biografia, :picture, :city_id)

    # Gem select2 doesn't send the city_id when none is selectd
    permitted_params.merge!(city_id: '') if params[:user][:city_id].nil?
    permitted_params
  end

  def password_params
    params.require(:user).permit :password, :password_confirmation, :current_password
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper

  def specific_error_for(field_name, options)
    resource = options[:resource]
    if resource.errors[field_name].any?
      content_tag(:div, class: 'specific-error') do
        resource.errors.full_messages_for(field_name).each do |error|
          concat(
            content_tag(:span, class: 'error') do
              error
            end
          )
        end
      end
    end
  end

end

app/helpers/menu_helper.rb
module MenuHelper
  def active_menu(controller_name)
    controller.controller_name == controller_name.to_s ? 'active' : ''
  end
end

app/views/candidatos/_menu.html.erb
<div class="col-md-3">
  <div class="col-md-12 white-box">
    <div class="row row-form">
      <%= image_tag @user.picture.url(:medium), class: 'img-rounded center-block profile-picture' %>
    </div>
    <div class="row">
      <ul class="nav nav-pills nav-stacked nav-candidato center-block">
        <li>
          <%= link_to biografia_candidato_path do %>
            <%= content_tag :i, nil, class: 'fa fa-male' %>
            Biografia
          <% end %>
        </li>
        <li>
          <%= link_to propostas_candidato_path do %>
            <%= content_tag :i, nil, class: 'fa fa-lightbulb-o' %>
            Propostas
          <% end %>
        </li>
        <li role="presentation">
          <a href="#">
            <i class="fa fa-camera"></i>
            Fotos
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/candidatos/biografia.html.erb
<div class="container">
  <div class="row">
    <%= render 'candidatos/menu' %>

    <div class="col-md-9">
      <div class="col-md-12 white-box">
        <div class="row">
          <div class="col-md-12">
            <h2 class="profile-title">
              <%= @user.name %>
            </h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-justify text">
            <%= raw @user.biografia.gsub(/\n/, '<br />') if @user.biografia.present? %>
          </div>
        </div>
    </div>
    </div>
  </div>
</div>

app/views/candidatos/index.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="col-md-12 white-box">
      <div class="row">
        <div class="col-md-8">
          <h2 class="profile-title">Candidatos</h2>
          <p class="margim-b">
            Conheça mais sobre os candidatos
          </p>
        </div>
      </div>
      <% @candidatos.each do |candidato| %>
        <div class="row row-form">
          <div class="col-md-12">
            <div class="col-md-2 text-center">
              <div class="row">
                <%= image_tag candidato.picture.url(:thumb), class: 'img-rounded-tiny' %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="row">
                <%= link_to candidato.name, biografia_candidato_path(candidato) %>
              </div>
              <div class="row">
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 white-box">
    <div class="col-md-12">
    </div>
  </div>
</div>

app/views/candidatos/propostas.html.erb
<div class="container">
  <div class="row">
    <%= render 'candidatos/menu' %>

    <div class="col-md-9">
      <div class="col-md-12 white-box">
        <div class="row">
          <div class="col-md-12">
            <h2 class="profile-title">
              <%= @user.name %>
            </h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-7">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cidades/show.html.erb
<% @cidades.each do |cidade| %>
  <option value="<%= cidade.id %>"><%= cidade.name %></option>
<% end %>

app/views/comments/_comments.html.erb
<% @comments.each do |comment| %>
  <div class="row">
    <div class="col-md-12 comment-box">
      <div class="col-md-2">
        <%= image_tag comment.user.picture.url(:medium), class: 'comment-profile-picture' %>
      </div>
      <div class="col-md-10">
        <div class="row">
          <em class="demanda-autor">
            <%= comment.user.name %> em <%= comment.created_at.to_formatted_s(:long) %>
          </em>
        </div>
        <div class="row">
          <%= comment.content %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-12">
        <%= form_for [@demanda, Comment.new], remote: true do |f| %>
          <%= f.text_area :content, class: 'form-control', placeholder: "Insira um comentário" %>

          <%= f.submit "Comentar", class: 'btn btn-success btn-form pull-right' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$(".row-comentarios").empty().append("<%= j render partial: 'comments/comments' %>")

app/views/demandas/_form.html.erb
<%= form_for @demanda, remote: true do |f| %>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <div class="row row-form">
    <%= f.text_field :titulo, class: 'form-control', placeholder: 'Título' %>
    <%= specific_error_for :titulo, resource: @demanda %>
  </div>
  <div class="row row-form">
    <%= f.text_area :descricao, class: 'form-control', rows: 10,
      placeholder: 'Descreva o problema de sua região' %>
    <%= specific_error_for :descricao, resource: @demanda %>
  </div>
  <div class="row row-form">
    <%= f.collection_select :demanda_categoria_id, DemandaCategoria.all, :id, :name,
        {prompt: "Selecione uma categoria"}, class: "form-control" %>
    <%= specific_error_for :demanda_categoria_id, resource: @demanda %>
    <%= specific_error_for :endereco, resource: @demanda %>
  </div>
  <div class="row">
    <%= f.submit 'Criar demanda', class: 'pull-right btn btn-success' %>
  </div>
<% end %>

app/views/demandas/create.js.erb
$(".form-container").empty().append("<%= j render(partial: 'demandas/form') %>")

app/views/demandas/index.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="col-md-12 white-box">
      <div class="row">
        <div class="col-md-8">
          <h2 class="profile-title">Demandas</h2>
          <p class="margim-b">
            Últimas demandas criadas pelos eleitores.
          </p>
        </div>
        <div class="col-md-4">
          <%= link_to "Criar nova demanda", new_demanda_path, class: 'pull-right btn btn-success',
            data: {no_turbolink: true} %>
        </div>
      </div>
      <% @demandas.each do |demanda| %>
        <div class="row row-form">
          <div class="col-md-12">
            <div class="col-md-2 text-center">
              <div class="row">
                <%= image_tag demanda.user.picture.url(:thumb), class: 'img-rounded-tiny' %>
              </div>
            </div>
            <div class="col-md-10">
              <div class="row">
                <h3 class="profile-title">
                  <%= image_tag demanda.demanda_categoria.try(:image_name), class: 'icone-categoria-demanda' %>
                  <%= link_to demanda.titulo, demanda_path(demanda), class: "demanda-title", data: {no_turbolink: true} %>
                </h3>
              </div>
              <div class="row">
                <em class="demanda-autor">Criada por <%= demanda.user.name %> em <%= demanda.created_at.to_formatted_s(:long) %></em>
              </div>
              <div class="row text-justify text">
                <% if demanda.descricao.size >= 400 %>
                  <%= demanda.descricao[0..400] + "..." %>
                <% else %>
                  <%= demanda.descricao %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 white-box">
    <div class="col-md-12">
    </div>
  </div>
</div>

app/views/demandas/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 white-box">
      <div class="row">
        <div class="col-md-1">
          <%= image_tag 'strike' %>
        </div>
        <div class="col-md-11">
          <h2 class="profile-title">Criar uma nova Demanda</h2>
          <p class="margim-b">
            Selecione a cidade e crie uma nova demanda para sua região.</br>
            Aguarde algum candidato assumir a responsabilidade.
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div id="mapa" style="height:400px;">
          </div>
          <input id="pac-input" class="controls" type="text">
        </div>
        <div class="col-md-4 form-container">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/demandas/show.html.erb
<%= hidden_field_tag :latitude, @demanda.latitude %>
<%= hidden_field_tag :longitude, @demanda.longitude %>

<div class="row">
  <div class="col-md-12 white-box">
    <!-- Mapa e título -->
    <div class="row row-form">
      <div class="col-md-1">
        <%= image_tag @demanda.user.picture.url(:medium), class: "img-rounded-tiny" %>
      </div>
      <div class="col-md-5">
        <div class="row">
          <h3 class="profile-title">
            <%= image_tag @demanda.demanda_categoria.try(:image_name), class: 'icone-categoria-demanda' %>
            <span class="demanda-title"><%= @demanda.titulo %></span>
          </h3>
        </div>
        <div class="row">
          <em class="demanda-autor">Criada por <%= @demanda.user.name %> em <%= @demanda.created_at.to_formatted_s(:long) %></em>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <h3 class="profile-title">
            <%= image_tag "map-paper", class: "icone-categoria-demanda" %>
            <span class="demanda-title">Localização</span>
          </h3>
        </div>
        <div class="row">
          <em class="demanda-autor">
            Veja no mapa onde está ocorrendo o problema.
          </em>
        </div>
      </div>
    </div>
    <!-- Descrição da demanda e mapa -->
    <div class="row">
      <div class="col-md-1">
      </div>
      <div class="col-md-5">
        <div class="row row-form text-justify text">
          <%= @demanda.descricao %>
        </div>
        <div class="row text row-comentarios">
          <%= render "comments/comments", locals: @comments %>
        </div>
      </div>
      <div class="col-md-6">
        <div id="mapa-demanda" style="height:400px;">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ficha Nova</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDXFnxMatHeFxTMWYQwZa-Z1T1V1wreaik&libraries=places' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

<div class="row">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container container-main-menu">
      <ul class="nav navbar-nav">
        <li class="<%= active_menu :home %>">
          <%= link_to "Home", root_path %>
        </li>
        <li class="<%= active_menu :candidatos %>">
          <%= link_to "Candidatos", candidatos_path %>
        </li>
        <li class="<%= active_menu :demandas %>">
          <%= link_to "Demandas", demandas_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to settings_profile_path, class: "paddingless", data: {no_turbolink: true} do %>
            <%= image_tag "edit-user", class: 'icon-menu' %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "paddingless" do %>
            <%= image_tag "shutdown", class: 'icon-menu' %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</div>

<div class="container main">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ficha Nova</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDXFnxMatHeFxTMWYQwZa-Z1T1V1wreaik&libraries=places' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body class="auth">

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/profiles/edit.html.erb
<div class="col-md-12 white-box">
  <%= form_for @user, url: settings_profile_path, html: {multipart: true, method: :put} do |f| %>
    <%= hidden_field_tag :city_data, (@user.city.present? ? "#{@user.city.id}|#{@user.city.name}" : "|") %>

    <div class="row row-form">
      <div class="col-md-2">
        <%= image_tag "edit-user", class: "pull-right" %>
      </div>
      <div class="col-md-4">
        <div class="row">
          <h2>Profile</h2>
        </div>
        <div class="row">
          <p class="margim-b">
            Crie um profile interessante e completo para que seus eleitores ou candidatos o vejam.
          </p>
        </div>
      </div>
      <div class="col-md-2">
        <%= image_tag "change-password", class: "pull-right" %>
      </div>
      <div class="col-md-4">
        <div class="row">
          <h2>Mudar Senha</h2>
        </div>
        <div class="row">
          <p class="margim-b">
            Mude a senha quando se sentir inconfortável com a segurança.
          </p>
        </div>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-2">
        <%= f.label :email, class: 'label-form pull-right' %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :email, class: 'form-control' %>
        <%= specific_error_for :email, resource: @user %>
      </div>
      <div class="col-md-6 text-center">
        <%= link_to "Trocar senha", settings_password_path, class: "btn btn-warning" %>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-2">
        <%= f.label :name, class: 'label-form pull-right' %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :name, class: 'form-control' %>
        <%= specific_error_for :name, resource: @user %>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-2">
        <%= f.label :username, class: 'label-form pull-right' %>
      </div>
      <div class="col-md-4">
        <%= f.text_field :username, class: 'form-control' %>
        <%= specific_error_for :username, resource: @user %>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-2">
        <%= f.label :city_id, class: "label-form pull-right" %>
      </div>
      <div class="col-md-4">
        <%= f.select :city_id, [], {prompt: "Selecione uma cidade"}, {class: "form-control"} %>
        <%= specific_error_for :city_id, resource: @user %>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-2">
        <%= f.label :biografia, class: 'pull-right' %>
      </div>
      <div class="col-md-4">
        <%= f.text_area :biografia, class: 'form-control', rows: 6 %>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-2">
        <% if @user.picture.present? %>
          <%= image_tag @user.picture.url(:thumb), class: 'img-rounded pull-right' %>
        <% else %>
          <%= image_tag @user.picture.url(:thumb), class: 'img-rounded-tiny pull-right' %>
        <% end %>
      </div>
      <div class="col-md-2">
        <%= f.file_field :picture %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <%= f.submit 'Alterar Perfil', class: 'btn btn-primary pull-right' %>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/edit_password.html.erb
<div class="col-md-12 white-box">
  <%= form_for @user, url: settings_password_path, html: {multipart: true, method: :put} do |f| %>

    <div class="row row-form">
      <div class="col-md-6 text-center">
        <h3>Change your password</h3>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-3">
        <%= f.label :current_password, class: 'label-form pull-right' %>
      </div>
      <div class="col-md-4">
        <%= f.password_field :current_password, class: 'form-control' %>
        <%= specific_error_for :current_password, resource: @user %>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-3">
        <%= f.label :password, class: 'label-form pull-right' %>
      </div>
      <div class="col-md-4">
        <%= f.password_field :password, class: 'form-control' %>
        <%= specific_error_for :password, resource: @user %>
      </div>
    </div>

    <div class="row row-form">
      <div class="col-md-3">
        <%= f.label :password_confirmation, class: 'label-form pull-right' %>
      </div>
      <div class="col-md-4">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= specific_error_for :password_confirmation, resource: @user %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-7">
        <%= f.submit 'Alterar Senha', class: 'btn btn-danger pull-right' %>
      </div>
    </div>
  <% end %>
</div>